# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."mcserber-mc" = {
    image = "itzg/minecraft-server:latest";
    environment = {
      "DIFFICULTY" = "2";
      "ENABLE_COMMAND_BLOCK" = "true";
      "ENABLE_WHITELIST" = "true";
      "EULA" = "TRUE";
      "HIDE_ONLINE_PLAYERS" = "true";
      "ICON" = "https://cdn.discordapp.com/icons/1447411301411197001/25b44cf084feee778e43d0fff987c27c.webp?size=512";
      "MEMORY" = "5120M";
      "MODRINTH_LOADER" = "fabric";
      "MODRINTH_MODPACK" = "./serberpack.mrpack";
      "MOTD" = "ebic minceraft serber";
      "ONLINE_MODE" = "false";
      "RESOURCE_PACK" = "https://download.mc-packs.net/pack/043db42f771efa012d69b83a4d776ae08eb1c83c.zip";
      "RESOURCE_PACK_PROMPT" = "pls download thx";
      "RESOURCE_PACK_REQUIRED" = "true";
      "RESOURCE_PACK_SHA1" = "043db42f771efa012d69b83a4d776ae08eb1c83c";
      "SEED" = "4958145370078478047";
      "SIMULATION_DISTANCE" = "6";
      "TYPE" = "MODRINTH";
      "USE_MEOWICE_FLAGS" = "true";
      "VERSION" = "1.21.10";
      "VIEW_DISTANCE" = "8";
    };
    volumes = [
      "/data/mc:/data:rw"
    ];
    ports = [
      "25565:25565/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=mc"
      "--network=mcserber_default"
    ];
  };
  systemd.services."podman-mcserber-mc" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-mcserber_default.service"
    ];
    requires = [
      "podman-network-mcserber_default.service"
    ];
    partOf = [
      "podman-compose-mcserber-root.target"
    ];
    wantedBy = [
      "podman-compose-mcserber-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-mcserber_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f mcserber_default";
    };
    script = ''
      podman network inspect mcserber_default || podman network create mcserber_default
    '';
    partOf = [ "podman-compose-mcserber-root.target" ];
    wantedBy = [ "podman-compose-mcserber-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-mcserber-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
